### PR TITLE
Additional samples

### PR DESCRIPTION
**Pull request by z3dev**
New sample files for AMF, STL, and X3D

### CODE REVIEW

**Comment by hrgdavor** [comment]
Is this supposed to be tested ? I am fine with adding the samples, but what are we doing with them ? :)

**Comment by z3dev** [comment]
> Is this supposed to be tested ? I am fine with adding the samples, but what are we doing with them ? :)

Collecting… as some examples are very hard to find in the wild.

I use these when testing major changes as well. But it’s basically manual testing of the WEB UI or CLI.

**Review by hrgdavor — APPROVED** [review]
This is a big list :) ... nice addition of examples. 👍

**Comment by z3dev** [comment]
> This is a big list :) ... nice addition of examples. 👍

Yeah. This is just nice to have around. GitHub doesn’t care so let’s take advantage of the free storage space. 😃

**Pull request merged**
